### ISSUE TITLE
'AADSTS50126: Error validating credentials due to invalid username or password.')

### ISSUE THREAD

**Issue by sant3e** [iamlu-coding/python-download-sharepoint-file#1]
I'm trying to dl an excel file from my organization's sharepoint
I used the files from here and I'm getting this error:

Traceback (most recent call last):
  File "C:\Users\tdiacon\Pyproj\PySharePoint\project.py", line 10, in <module>
    file  = SharePoint().download_file(file_name, folder_name)
  File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 37, in download_file
    self._folder = self.connect_folder(folder_name)
  File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 29, in connect_folder
    self.auth_site = self.auth()
  File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 23, in auth
    self.authcookie = Office365(SHAREPOINT_URL, username=USERNAME, password=PASSWORD).GetCookies()
  File "C:\Users\tdiacon\Pyproj\PySharePoint\venv\lib\site-packages\shareplum\office365.py", line 88, in get_cookies
    sectoken = self.get_security_token(self.username, self.password)
  File "C:\Users\tdiacon\Pyproj\PySharePoint\venv\lib\site-packages\shareplum\office365.py", line 80, in get_security_token
    raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50126: Error validating credentials due to invalid username or password.')

Any ideas?

**Comment by iamlu-coding** [comment]
Hello

Can you confirm that your user and password doesn’t contain the { } characters?  These are just place holders for the actual value.

Lu

From: sant3e ***@***.***>
Sent: Wednesday, March 30, 2022 6:46 AM
To: iamlu-coding/python-download-sharepoint-file ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iamlu-coding/python-download-sharepoint-file] 'AADSTS50126: Error validating credentials due to invalid username or password.') (Issue #1)


I'm trying to dl an excel file from my organization's sharepoint
I used the files from here and I'm getting this error:

Traceback (most recent call last):
File "C:\Users\tdiacon\Pyproj\PySharePoint\project.py", line 10, in
file = SharePoint().download_file(file_name, folder_name)
File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 37, in download_file
self._folder = self.connect_folder(folder_name)
File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 29, in connect_folder
self.auth_site = self.auth()
File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 23, in auth
self.authcookie = Office365(SHAREPOINT_URL, username=USERNAME, password=PASSWORD).GetCookies()
File "C:\Users\tdiacon\Pyproj\PySharePoint\venv\lib\site-packages\shareplum\office365.py", line 88, in get_cookies
sectoken = self.get_security_token(self.username, self.password)
File "C:\Users\tdiacon\Pyproj\PySharePoint\venv\lib\site-packages\shareplum\office365.py", line 80, in get_security_token
raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50126: Error validating credentials due to invalid username or password.')

Any ideas?

**Comment by sant3e** [comment]
No {} ... in my config.json i have:
"user":"myname@mydomain.com",
"password":"password_text"

If it matters (!?) I have an @ in my password (the domain forces me to have a character like that)

**Comment by iamlu-coding** [comment]
I believe @ characters are ok but not sure.

I have had some issues in the past related to specific special characters, I just can’t remember which character I had issues with.

Besides that everything looks good. Your user name look ok.

Lu

**Comment by sant3e** [comment]
Might this be related to mydomain requiring MFA (I'm not really sure on that though, if it is ... it probably asked me to confirm the login and after that it never bothered me about it again .. so i simply don't remember if it asked for something extra or not. If i log out and re-login ... now... it doesn't have any extra step). Let's just assume the domain has a 2FA setup ... would this be an issue? If yes, any solution you can provide? Thank you for your assistance!

**Comment by iamlu-coding** [comment]
So if company has MFA setup you will get an error but it will be a different error.

The error you are getting is the same error I received sometime back and for me it was due to my password having a specific special character.  I do have special character in my password but there was a special one that caused issues.  It may be the @ character I just can't remember.

Lu

Sent via the Samsung Galaxy Z Fold3 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sant3e** [comment]
I've changed my password and run it again. Now i get this:

Traceback (most recent call last):
  File "C:\Users\tdiacon\Pyproj\PySharePoint\project.py", line 5, in <module>
    clients = SharePoint().connect_to_list(ls_name='SPG Change Initiation Request')
  File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 36, in connect_to_list
    self.auth_site = self.auth()
  File "C:\Users\tdiacon\Pyproj\PySharePoint\sharepoint.py", line 23, in auth
    self.authcookie = Office365(
  File "C:\Users\tdiacon\Pyproj\PySharePoint\venv\lib\site-packages\shareplum\office365.py", line 88, in get_cookies
    sectoken = self.get_security_token(self.username, self.password)
  File "C:\Users\tdiacon\Pyproj\PySharePoint\venv\lib\site-packages\shareplum\office365.py", line 80, in get_security_token
    raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50059: No tenant-identifying information found in either the request 
or implied by any provided credentials.')

Is this it?
